java_library(
    name = "formatters",
    srcs = glob(["**/*.java"]),
    deps = [
        "//sub-modules:langtools",
        "//src/main/java/com/staircaselabs/jformatter/core:core"
    ],
    visibility = [
        "//src/main/java/com/staircaselabs/jformatter:__pkg__",
        "//src/test/java/com/staircaselabs/jformatter/formatters:__pkg__",
    ],
)
