java_library(
    name = "formatters",
    srcs = glob(["**/*.java"]),
    deps = [
        "//sub-modules:langtools",
        "//src/main/java/com/staircaselabs/jformatter/config:config",
        "//src/main/java/com/staircaselabs/jformatter/core:core",
        "//src/main/java/com/staircaselabs/jformatter/debug:debug",
    ],
    visibility = [
        "//:__pkg__",
        "//src/test/java/com/staircaselabs/jformatter/formatters:__pkg__",
    ],
)
