#package( default_visiblity = [ "//visibility:public" ] )

filegroup(
    name = "test-inputs",
    srcs = glob([ "*.java" ]),
    visibility = [ "//src/test/java/com/staircaselabs/jformatter:__subpackages__" ],
)
