java_library(
    name = "core",
    srcs = glob([ "*.java" ]),
    deps = [
        "@yamlbeans//jar",
        "//sub-modules:langtools"
    ],
    visibility = [
        "//src/main/java/com/staircaselabs/jformatter:__pkg__",
        "//src/main/java/com/staircaselabs/jformatter/formatters:__pkg__",
        "//src/test/java/com/staircaselabs/jformatter/formatters:__pkg__",
    ],
)
