java_library(
    name = "core",
    srcs = glob([ "**/*.java" ]),
    deps = [
        "//sub-modules:langtools",
        "//src/main/java/com/staircaselabs/jformatter/debug:debug",
    ],
    visibility = [
        "//:__pkg__",
        "//src/main/java/com/staircaselabs/jformatter/config:__pkg__",
        "//src/main/java/com/staircaselabs/jformatter/formatters:__pkg__",
        "//src/test/java/com/staircaselabs/jformatter/formatters:__pkg__",
    ],
)
