# indentation
convertTabsToSpaces: true
tabWidth: 4

# padding
methodArguments: 1
groupingParentheses: 0
typeCasts: 0
typeParameters: 0
arrays: 1
trailingMethodNames: 0

# line-wrapping
maxLineWidth: 80
oneMethodArgumentPerLine: false
oneUnionElementPerLine: false
oneArrayElementPerLine: false
closingBracesOnNewLine: true
closingParenthesesOnNewLine: false
allowLineWrapAtMethodInvocationMemberSelect: true
allowLineWrapAtNewClassMemberSelect: true
allowLineWrapAtIdentifierMemberSelect: false

# number of tabs to insert after line-wrapping various tokens
arrayLineWrapTabs: 2
assignmentLineWrapTabs: 2
extendsLineWrapTabs: 2
implementsLineWrapTabs: 2
memberSelectLineWrapTabs: 1
methodArgumentLineWrapTabs: 2
ternaryLineWrapTabs: 2
throwsLineWrapTabs: 2
unionLineWrapTabs: 2
unboundListItemLineWrapTabs: 2

# miscellaneous
cuddleBraces: true
