# indentation
convertTabsToSpaces: true
tabWidth: 4

# padding
methodArguments: 1
groupingParentheses: 1
typeCasts: 1
typeParameters: 1
arrays: 1
trailingMethodNames: 0

# line-wrapping
maxLineWidth: 60
numTabsAfterLineWrap: 2
closingParenthesesOnNewLine: true
methodArgumentsOnNewLine: true

# miscellaneous
cuddleBraces: true
