# indentation
convertTabsToSpaces: true
tabWidth: 4
numTabsAfterLineWrap: 2

# padding
methodArguments: 1
groupingParentheses: 1
typeCasts: 1
typeParameters: 1
arrays: 1
trailingMethodNames: 0

# line-wrapping
maxLineWidth: 120
cuddleBraces: true
closingParenthesesOnNewLine: false
